routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use SebastianBergmann\CodeCoverage\Report\Html\Dashboard;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('back/dashboard/index');
// });
Route::get('/login',[LoginController::class,'index'])->name('login');
Route::post('/login-proses',[LoginController::class,'login_proses'])->name('login-proses');
Route::post('/logout',[LoginController::class,'logout'])->name('logout');


Route::group(['prepix' => 'admin','middleware' => ['auth'],'as'=>'admin.'], function(){
    Route::get('/dashboard',[DashboardController::class,'index'])->name('dashboard');
    Route::resource('/teams', \App\Http\Controllers\TeamController::class);
    Route::resource('/contacts', \App\Http\Controllers\ContactController::class);
    Route::resource('/evolutions', \App\Http\Controllers\EvolutionController::class);
    Route::resource('/company_goals', \App\Http\Controllers\CompanyGoalsController::class);
    Route::resource('/settings', \App\Http\Controllers\SettingController::class);
    Route::resource('/abouts', \App\Http\Controllers\AboutController::class);
    Route::resource('/clients', \App\Http\Controllers\ClientController::class);
    Route::resource('/homes', \App\Http\Controllers\HomeController::class);

});

Route::get('/register', [LoginController::class, 'register'])->name('register');

Route::post('/register', [LoginController::class, 'register_proses']);

app/Models/About.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class About extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'desc',
        'desc_about',
        'count_bussines',
        'count_member',
        'count_client',
        'count_project',
        'vision',
        'misi',
        'flag',
    ];
}

app/Http/Controllers/AboutController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\About;
use Illuminate\View\View;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $abouts = about::where('flag', 1)
        ->latest()
        ->paginate(5);

        return view('back/about.index', compact('abouts'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('back/about.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'desc_1' => 'required',
            'desc_2' =>'required',
            'image' => 'required|image',
            'vision' => 'required',
            'misi' => 'required',
            'count_target' => 'required',
            'count_Digital_Campaign' => 'required',
            'count_target_income' => 'required',
            'count_income' => 'required'
        ]);

        $image = $request->file('image');
        $image->storeAs('public/posts', $image->hashName());

        about::create([
        'desc_1' => $request->desc_1,
        'desc_2' => $request->desc_2,
        'image' => $image->hashName(),
        'vision' => $request->vision,
        'misi' => $request->misi,
        'count_target' => $request->count_target,
        'count_Digital_Campaign' => $request->count_Digital_Campaign,
        'count_target_income' => $request->count_target_income,
        'count_income' => $request->count_income,
        'flag' => 1,
    ]);
    return redirect()->route('admin.abouts.index')->with(['success' => 'Data Berhasil Disimpan!']);

    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //

        $about = about::findOrFail($id);

        return view('back/about.edit', compact('about'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
{
    $this->validate($request, [
        'logo' => 'image',
        'no_telephone' => '',
        'email' => '',
        'address' => '',
        'working_hours' => '',
        'maps' => '',
        'no_whatsapp' => '',
        'desc_1' => '',
        'desc_2' => '',
        'vision' => '',
        'misi' => '',
        'count_target' => '',
        'count_Digital_Campaign' => '',
        'count_target_income' => '',
        'count_income' => '',
    ]);

    // Get the setting by ID
    $about = about::findOrFail($id);

    // Check if an image is uploaded
    if ($request->hasFile('logo')) {
        // Upload new image
        $logo = $request->file('logo');
        $logo->storeAs('public/posts', $logo->hashName());

        // Delete old image
        Storage::delete('public/posts/' . $about->logo);

        // Update the about with the new image and other fields
        $about->update([
            'logo' => $logo->hashName(),
            'no_telephone' => $request->no_telephone,
            'email' => $request->email,
            'address' => $request->address,
            'working_hours' => $request->working_hours,
            'maps' => $request->maps,
            'no_whatsapp' => $request->no_whatsapp,
            'desc_1' => $request->desc_1,
            'desc_2' => $request->desc_2,
            'vision' => $request->vision,
            'misi' => $request->misi,
            'count_target' => $request->count_target,
            'count_Digital Campaign' => $request->count_Digital_Campaign,
            'count_target_income' => $request->count_target_income,
            'count_income' => $request->count_income,
        ]);
    } else {
        // Update the about without changing the image
        $about->update([
            'no_telephone' => $request->no_telephone,
            'email' => $request->email,
            'address' => $request->address,
            'working_hours' => $request->working_hours,
            'maps' => $request->maps,
            'no_whatsapp' => $request->no_whatsapp,
            'desc_1' => $request->desc_1,
            'desc_2' => $request->desc_2,
            'vision' => $request->vision,
            'misi' => $request->misi,
            'count_target' => $request->count_target,
            'count_Digital_Campaign' => $request->count_Digital_Campaign,
            'count_target_income' => $request->count_target_income,
            'count_income' => $request->count_income,
        ]);
    }

    // Redirect to the edit page
    return redirect()->route('admin.abouts.edit', 1)->with(['success' => 'Data Berhasil Diubah!']);
}


    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $abouts = about::findOrFail($id);
    
        // Mengubah nilai flag menjadi 0
        $abouts->update(['flag' => 0]);
    
        return redirect()->route('admin.abouts.index')->with(['success' => 'Data berhasil dihapus!']);
    }
    
}

resources/views/back/about/create.blade.php
@extends('back.layouts.app')
@section('content')
@push('styles-plugins')

@endpush

@push('styles')
<style>

</style>
@endpush

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow-sm rounded">
                    <div class="card-body">
                        <form action="{{ route('admin.abouts.store') }}" method="POST" enctype="multipart/form-data">
                        
                            @csrf

                            <div class="form-group">
                                <label class="font-weight-bold">DESC_1</label>
                                <textarea type="text" class="form-control @error('desc_1') is-invalid @enderror" name="desc_1" value="{{ old('desc_1') }}" placeholder="Masukkan desc_1"></textarea>
                            
                                <!-- error message untuk title -->
                                @error('desc_1')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">DESC_2</label>
                                <textarea type="text" class="form-control @error('desc_2') is-invalid @enderror" name="desc_2" value="{{ old('desc_2') }}" placeholder="Masukkan desc_2"></textarea>
                            
                                <!-- error message untuk title -->
                                @error('desc_2')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">GAMBAR</label>
                                <input type="file" class="form-control @error('image') is-invalid @enderror" name="image">
                            
                                <!-- error message untuk title -->
                                @error('image')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">VISION</label>
                                <input type="text" class="form-control @error('vision') is-invalid @enderror" name="vision" value="{{ old('vision') }}" placeholder="Masukkan vision">
                            
                                <!-- error message untuk title -->
                                @error('vision')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">MISI</label>
                                <textarea class="form-control @error('misi') is-invalid @enderror" name="misi" rows="5" placeholder="Masukkan misi">{{ old('misi') }}</textarea>
                            
                                <!-- error message untuk content -->
                                @error('misi')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">COUNT_TARGET</label>
                                <input type="text" class="form-control @error('count_target') is-invalid @enderror" name="count_target" value="{{ old('count_target') }}" placeholder="Masukkan count_target">
                            
                                <!-- error message untuk title -->
                                @error('count_target')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">count_Digital_Campaign</label>
                                <input type="text" class="form-control @error('count_Digital_Campaign') is-invalid @enderror" name="count_Digital_Campaign" value="{{ old('count_Digital_Campaign') }}" placeholder="Masukkan count_Digital_Campaign">
                            
                                <!-- error message untuk title -->
                                @error('count_Digital_Campaign')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">COUNT_TARGET_ICOME</label>
                                <input type="text" class="form-control @error('count_target_income') is-invalid @enderror" name="count_target_income" value="{{ old('count_target_income') }}" placeholder="Masukkan count_target_income">
                            
                                <!-- error message untuk title -->
                                @error('count_target_income')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">COUNT_INCOME</label>
                                <input type="text" class="form-control @error('count_income') is-invalid @enderror" name="count_income" value="{{ old('count_income') }}" placeholder="Masukkan count_income">
                            
                                <!-- error message untuk title -->
                                @error('count_income')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <button type="submit" class="btn btn-md btn-primary">SIMPAN</button>
                            <button type="reset" class="btn btn-md btn-warning">RESET</button>

                        </form> 
                    </div>
                </div>
            </div>
        </div>
    </div>
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
<script>
</script>
@push('scripts-plugins')

@endpush

@push('scripts')
<script>
    
 
</script>
@endpush
@endsection

resources/views/back/about/edit.blade.php
@extends('back.layouts.app')
@section('content')
@push('styles-plugins')

@endpush

@push('styles')
<style>

</style>
@endpush

<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-md-12">
            <div class="card border-0 shadow-sm rounded">
                <div class="card-body">
                    <form action="{{ route('admin.abouts.update', $about->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <!-- Tambahkan field desc_1 -->
                        <div class="form-group">
                            <label class="font-weight-bold">desc_1</label>
                            <textarea class="form-control @error('desc_1') is-invalid @enderror" name="desc_1" rows="5" placeholder="Masukkan desc_1">{{ old('desc_1', $about->desc_1) }}</textarea>
                        
                            <!-- error message untuk desc_1 -->
                            @error('desc_1')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>

                        <!-- Tambahkan field desc_2 -->
                        <div class="form-group">
                            <label class="font-weight-bold">desc_2</label>
                            <textarea class="form-control @error('desc_2') is-invalid @enderror" name="desc_2" rows="5" placeholder="Masukkan desc_2">{{ old('desc_2', $about->desc_2) }}</textarea>
                        
                            <!-- error message untuk desc_2 -->
                            @error('desc_2')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>

                        <!-- Tambahkan field image -->
                        <div class="form-group">
                            <label class="font-weight-bold">image</label>
                            <input type="file" class="form-control @error('image') is-invalid @enderror" name="image" value="{{ old('image', $about->image) }}">
                        
                            <!-- error message untuk image -->
                            @error('image')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>

                        <!-- Tambahkan field vision -->
                        <div class="form-group">
                            <label class="font-weight-bold">vision</label>
                            <textarea class="form-control @error('vision') is-invalid @enderror" name="vision" rows="5" placeholder="Masukkan vision">{{ old('vision', $about->vision) }}</textarea>
                        
                            <!-- error message untuk vision -->
                            @error('vision')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>

                        <!-- Tambahkan field misi -->
                        <div class="form-group">
                            <label class="font-weight-bold">misi</label>
                            <textarea class="form-control @error('misi') is-invalid @enderror" name="misi" rows="5" placeholder="Masukkan misi">{{ old('misi', $about->misi) }}</textarea>
                        
                            <!-- error message untuk misi -->
                            @error('misi')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>

                        <!-- Tambahkan field count_target -->
                        <div class="form-group">
                            <label class="font-weight-bold">count_target</label>
                            <input type="text" class="form-control @error('count_target') is-invalid @enderror" name="count_target" value="{{ old('count_target', $about->count_target) }}" placeholder="Masukkan count_target">
                        
                            <!-- error message untuk count_target -->
                            @error('count_target')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>

                        <!-- Tambahkan field count_Digital Campaign -->
                        <div class="form-group">
                            <label class="font-weight-bold">count_Digital_Campaign</label>
                            <input type="text" class="form-control @error('count_Digital Campaign') is-invalid @enderror" name="count_Digital Campaign" value="{{ old('count_Digital Campaign', $about->count_Digital_Campaign) }}" placeholder="Masukkan count_Digital Campaign">
                        
                            <!-- error message untuk count_Digital Campaign -->
                            @error('count_Digital Campaign')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>

                        <!-- Tambahkan field count_target_income -->
                        <div class="form-group">
                            <label class="font-weight-bold">count_target_income</label>
                            <input type="text" class="form-control @error('count_target_income') is-invalid @enderror" name="count_target_income" value="{{ old('count_target_income', $about->count_target_income) }}" placeholder="Masukkan count_target_income">
                        
                            <!-- error message untuk count_target_income -->
                            @error('count_target_income')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>

                        <!-- Tambahkan field count_income -->
                        <div class="form-group">
                            <label class="font-weight-bold">count_income</label>
                            <input type="text" class="form-control @error('count_income') is-invalid @enderror" name="count_income" value="{{ old('count_income', $about->count_income) }}" placeholder="Masukkan count_income">
                        
                            <!-- error message untuk count_income -->
                            @error('count_income')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>

                        <button type="submit" class="btn btn-md btn-primary">UPDATE</button>
                        <button type="reset" class="btn btn-md btn-warning">RESET</button>

                    </form> 
                </div>
            </div>
        </div>
    </div>
</div>
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'position' );
</script>
@push('scripts-plugins')

@endpush

@push('scripts')
<script>
    
 
</script>
@endpush
@endsection

resources/views/back/about/index.blade.php
@extends('back.layouts.app')
@section('content')
@push('styles-plugins')

@endpush

@push('styles')
<style>

</style>
@endpush

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <div>
                    <h3 class="text-center my-4">DATA ABOUT</h3>
                    <h5 class="text-center"><a href="https://santrikoding.com"></a></h5>         
                    <hr>

                </div>
                <div class="card border-0 shadow-sm rounded">
                    <div class="card-body">
                        <a href="{{ route('admin.abouts.create') }}" class="btn btn-md btn-success mb-3">ADD ABOUT</a>
                        <table class="table table-bordered">
                            <thead>
                              <tr>
                                  <th scope="col">Image</th>
                                <th scope="col">Desc 1</th>
                                <th scope="col">Desc 2</th>
                                <th scope="col">Vision</th>
                                <th scope="col">Misi</th>
                                <th scope="col">Count Target</th>
                                <th scope="col">Count Digital Campaign</th>
                                <th scope="col">Count Target Income</th>
                                <th scope="col">Count Income</th>
                                <th scope="col">aksi</th>

                              </tr>
                            </thead>
                            <tbody>
                              @forelse ($abouts as $post)
                                <tr>
                                    <td class="text-center">
                                        <img src="{{ asset('/storage/posts/'.$post->image) }}" class="rounded" style="width: 150px">
                                    </td>
                                    <td>{!! $post->desc_1 !!}</td>
                                    <td>{!! $post->desc_2 !!}</td>
                                    <td>{!! $post->vision !!}</td>
                                    <td>{!! $post->misi !!}</td>
                                    <td>{!! $post->count_target !!}</td>
                                    <td>{!! $post->count_Digital_Campaign !!}</td>
                                    <td>{!! $post->count_target_income !!}</td>
                                    <td>{!! $post->count_income !!}</td>

                                    <td class="text-center">
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('admin.abouts.destroy', $post->id) }}" method="POST">
                                            <a href="{{ route('admin.abouts.edit', $post->id) }}" class="btn btn-sm btn-primary">EDIT</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">HAPUS</button>
                                            
                                        </form>
                                    </td>
                                </tr>
                              @empty
                                  <div class="alert alert-danger">
                                      Data Post belum Tersedia.
                                  </div>
                              @endforelse
                            </tbody>
                          </table>  
                          {{ $abouts->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script>
        //message with toastr
        @if(session()->has('success'))
        
            toastr.success('{{ session('success') }}', 'BERHASIL!'); 

        @elseif(session()->has('error'))

            toastr.error('{{ session('error') }}', 'GAGAL!'); 
            
        @endif
    </script>

@push('scripts-plugins')

@endpush

@push('scripts')
<script>
    
 
</script>
@endpush
@endsection