routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use SebastianBergmann\CodeCoverage\Report\Html\Dashboard;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('back/dashboard/index');
// });
Route::get('/login',[LoginController::class,'index'])->name('login');
Route::post('/login-proses',[LoginController::class,'login_proses'])->name('login-proses');
Route::post('/logout',[LoginController::class,'logout'])->name('logout');


Route::group(['prepix' => 'admin','middleware' => ['auth'],'as'=>'admin.'], function(){
    Route::get('/dashboard',[DashboardController::class,'index'])->name('dashboard');
    Route::resource('/teams', \App\Http\Controllers\TeamController::class);
    Route::resource('/contacts', \App\Http\Controllers\ContactController::class);
    Route::resource('/evolutions', \App\Http\Controllers\EvolutionController::class);
    Route::resource('/company_goals', \App\Http\Controllers\CompanyGoalsController::class);
    Route::resource('/settings', \App\Http\Controllers\SettingController::class);
    Route::resource('/abouts', \App\Http\Controllers\AboutController::class);
    Route::resource('/clients', \App\Http\Controllers\ClientController::class);
    Route::resource('/homes', \App\Http\Controllers\HomeController::class);

});

Route::get('/register', [LoginController::class, 'register'])->name('register');

Route::post('/register', [LoginController::class, 'register_proses']);

app/Models/evolution.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class evolution extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'years_record',
        'desc',
        'flag'
    ];
}

app/Http/Controllers/EvolutionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\evolution;
use Illuminate\View\View;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class EvolutionController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    
    public function index()
{
    $evolutions = evolution::where('flag', 1)
                ->latest()
                ->paginate(5);

    return view('back/evolution.index', compact('evolutions'));
}

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('back/evolution.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'years_record' => '',
            'desc' => ''
        ]);

        evolution::create([
            'years_record' => $request->years_record,
            'desc' => $request->desc,
            'flag' => 1
        ]);

        return redirect()->route('admin.evolutions.index')->with(['success' => 'Data Berhasil Disimpan!']);

    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $evolutions = evolution::findOrFail($id);

        return view('back/evolution.edit', compact('evolutions'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $this->validate($request, [
            'years_record' => 'required',
            'desc' => 'required'
        ]);

        $evolutions = evolution::findOrFail($id);


        $evolutions->update([
            'years_record' => $request->years_record,
            'desc' => $request->desc,
            
        ]);

        return redirect()->route('admin.evolutions.index')->with(['success' => 'Data Berhasil di ubah!']);

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $evolutions = evolution::findOrFail($id);
    
        // Mengubah nilai flag menjadi 0
        $evolutions->update(['flag' => 0]);
    
        return redirect()->route('admin.evolutions.index')->with(['success' => 'Data berhasil dihapus!']);
    }
}

resources/views/back/evolution/create.blade.php
@extends('back.layouts.app')
@section('content')
@push('styles-plugins')

@endpush

@push('styles')
<style>

</style>
@endpush

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow-sm rounded">
                    <div class="card-body">
                        <form action="{{ route('admin.evolutions.store') }}" method="POST" enctype="multipart/form-data">
                        
                            @csrf

                            

                            <div class="form-group">
                                <label class="font-weight-bold">YEARS_RECORD</label>
                                <input type="text" class="form-control @error('years_record') is-invalid @enderror" name="years_record" value="{{ old('years_record') }}" placeholder="Masukkan years">
                            
                                <!-- error message untuk title -->
                                @error('years_record')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">DESC</label>
                                <textarea class="form-control @error('desc') is-invalid @enderror" name="desc" rows="5" placeholder="Masukkan desc">{{ old('desc') }}</textarea>
                            
                                <!-- error message untuk content -->
                                @error('desc')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <button type="submit" class="btn btn-md btn-primary">SIMPAN</button>
                            <button type="reset" class="btn btn-md btn-warning">RESET</button>

                        </form> 
                    </div>
                </div>
            </div>
        </div>
    </div>
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'desc' );
</script>
@push('scripts-plugins')

@endpush

@push('scripts')
<script>
    
 
</script>
@endpush
@endsection

resources/views/back/evolution/edit.blade.php
@extends('back.layouts.app')
@section('content')
@push('styles-plugins')

@endpush

@push('styles')
<style>

</style>
@endpush

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow-sm rounded">
                    <div class="card-body">
                        <form action="{{ route('admin.evolutions.update', $evolutions->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')

                        

                            <div class="form-group">
                                <label class="font-weight-bold">YEARS_RECORD</label>
                                <input type="text" class="form-control @error('years_record') is-invalid @enderror" name="years_record" value="{{ old('years_record', $evolutions->years_record) }}" placeholder="Masukkan years">
                            
                                <!-- error message untuk title -->
                                @error('years_record')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">DESC</label>
                                <textarea class="form-control @error('desc') is-invalid @enderror" name="desc" rows="5" placeholder="Masukkan desc">{{ old('desc', $evolutions->desc) }}</textarea>
                            
                                <!-- error message untuk content -->
                                @error('desc')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <button type="submit" class="btn btn-md btn-primary">UPDATE</button>
                            <button type="reset" class="btn btn-md btn-warning">RESET</button>

                        </form> 
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'desc' );
</script>
@push('scripts-plugins')

@endpush

@push('scripts')
<script>
    
 
</script>
@endpush
@endsection

resources/views/back/evolution/index.blade.php
@extends('back.layouts.app')
@section('content')
@push('styles-plugins')

@endpush

@push('styles')
<style>

</style>
@endpush

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <div>
                    <h3 class="text-center my-4">DATA EVOLUTION</h3>
                    <h5 class="text-center"><a href="https://santrikoding.com"></a></h5>         
                    <hr>

                </div>
                <div class="card border-0 shadow-sm rounded">
                    <div class="card-body">
                        <a href="{{ route('admin.evolutions.create') }}" class="btn btn-md btn-success mb-3">ADD EVOLUTION</a>
                        <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th scope="col">YEARS_RECORD</th>
                                <th scope="col">DESC</th>
                                <th scope="col">AKSI</th>
                              </tr>
                            </thead>
                            <tbody>
                              @forelse ($evolutions as $post)
                                <tr>
                                   
                                    <td>{{ $post->years_record }}</td>
                                    <td>{!! $post->desc !!}</td>
                                    <td class="text-center">
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('admin.evolutions.destroy', $post->id) }}" method="POST">
                                            <a href="{{ route('admin.evolutions.edit', $post->id) }}" class="btn btn-sm btn-primary">EDIT</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">HAPUS</button>
                                            
                                        </form>
                                    </td>
                                </tr>
                              @empty
                                  <div class="alert alert-danger">
                                      Data Post belum Tersedia.
                                  </div>
                              @endforelse
                            </tbody>
                          </table>  
                          {{ $evolutions->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script>
        //message with toastr
        @if(session()->has('success'))
        
            toastr.success('{{ session('success') }}', 'BERHASIL!'); 

        @elseif(session()->has('error'))

            toastr.error('{{ session('error') }}', 'GAGAL!'); 
            
        @endif
    </script>

@push('scripts-plugins')

@endpush

@push('scripts')
<script>
    
 
</script>
@endpush
@endsection